---
"$schema": "http://json-schema.org/schema#"
"title": "Schema validation for Gammapy high-level interface API configuration"

type: object
additionalProperties: true
properties:

    general:
        description: "General settings for the API."
        type: object
        default: {"logging": {}}
        additionalProperties: false
        properties:
            outdir:
                description: "Output folder where files will be stored."
                type: string
                default: "."
            logging:
                description: "Logging settings for the session."
                type: object
                default: {"level": ""}
                additionalProperties: false
                properties:
                    level:
                        description: ""
                        type: string
                        default: INFO
                        enum: [CRITICAL, 50,
                               ERROR, 40,
                               WARNING, 30,
                               INFO, 20,
                               DEBUG, 10,
                               NOTSET]
                    filename: {type: string}
                    filemode: {type: string}
                    format: {type: string}
                    datefmt: {type: string}
                required: [level]
                dependencies:
                    filemode: [filename]
        required: [logging]
#    general:
#        logging:
#            level: INFO
#            filename: mylogfile.log
#            filemode: w
#            format: "%(asctime)s - %(message)s"
#            datefmt: "%d-%b-%y %H:%M:%S"
#        outdir: .

    observations:
        description: "Observations used in the analysis."
        type: object
        default: {}
        additionalProperties: false
        properties:
            datastore:
                description: "Data store where to fetch observations."
                type: string
                default:
                    $GAMMAPY_DATA/hess-dl3-dr1
            filters:
                description: "Array of filters with selection criteria."
                type: array
                default: [{}]
                items:
                    type: object
                    additionalProperties: false
                    properties:
                        exclude: {type: boolean}
                        inverted: {type: boolean}
                        filter_type:
                            default: par_value
                            enum: [sky_circle,
                                   angle_box,
                                   par_box,
                                   par_value,
                                   ids,
                                   all]
                        frame:
                            enum: [galactic, equatorial, icrs, fk5]
                        lon: {type: number}
                        lat: {type: number}
                        radius: {type: number}
                        border: {type: number}
                        variable: {type: string, default: TARGET_NAME}
                        value_param: {type: string, default: Crab}
                        value_range:
                            type: array
                            items: {type: number}
                            minItems: 2
                            maxItems: 2
                        obs_ids:
                            type: array
                            items: {type: integer}
                    required: [filter_type]
        required: [datastore]
#    observations:
#        datastore: $GAMMAPY_DATA/hess-dl3-dr1
#        filters:
#            - filter_type: sky_circle, angle_box, par_box, par_value, ids, all
#              frame: galactic, equatorial, icrs, fk5
#              lon: 83.633 deg
#              lat: 22.014 deg
#              radius: 1 deg
#              border: 1 deg
#              variable: TARGET_NAME
#              value_param: Crab
#              value_range:
#              - 265 deg
#              - 268 deg
#              obs_ids: [23523, 23526]
#           exclude: false
#           inverted: false

    reduction:
        description: "Process of data reduction."
        type: object
        default: {}
        additionalProperties: false
        properties:
            background:
                type: object
                default: {}
                additionalProperties: false
                properties:
                    background_estimator:
                        default: reflected
                        enum: [reflected, ring]
                    on_region:
                        type: object
                        default: {}
                        additionalProperties: false
                        properties:
                            center:
                                type: array
                                items: {type: number}
                                default: [83.633 deg, 22.014 deg]
                                minItems: 2
                                maxItems: 2
                            radius:
                                type: number
                                default: 0.1 deg
                            frame:
                                default: icrs
                                enum: [galactic, equatorial, icrs, fk5]
                    exclusion_mask:
                        description: "Filename of a FITS file."
                        type: object
                        additionalProperties: false
                        properties:
                            filename:
                                type: string
                            hdu:
                                type: string
                if:
                    properties:
                        exclusion_mask:
                            required: [filename]
            data_reducer:
                default: 1d
                enum: [1d, 2d, 3d]
            containment_correction:
                type: boolean
                default: true
        if:
            properties:
                data_reducer:
                    const: 1d
        then:
            properties:
                background:
                    required: [background_estimator, on_region]
#        background:
#            background_estimator: reflected
#            on_region:
#                center:
#                - 83.633 deg
#                - 22.014 deg
#                frame: icrs
#                radius: 0.11 deg
#            exclusion_mask
#                filename: mask.fits
#                hdu: IMAGE
#        containment_correction: true
#        data_reducer: 1d

    geometry:
        description: "Geometry where to perform data reduction and analysis."
        type: object
        default: {}
        additionalProperties: false
        properties:
            binsz:
                description: "Map pixel size in degrees."
                type: number
            coordsys:
                description: "Coordinate system."
                type: string
                enum: [CEL, GAL]
            proj:
                description: "Any valid WCS projection type."
                type: string
            skydir:
                description: "Lon and lat in deg in the coordsys of the map."
                type: array
                items: {type: number}
                minItems: 2
                maxItems: 2
            width:
                description: "Width of the map in degrees."
                type: array
                items: {type: number}
                minItems: 1
                maxItems: 2
            offset_max:
                type: number
            axes:
                type: object
                default: {}
                additionalProperties: false
                properties:
                    e_reco:
                        "$ref": "#/definitions/energy_axis"
                    e_true:
                        "$ref": "#/definitions/energy_axis"
#    geometry:
#        binsz: 0.02
#        coordsys: CEL, GAL
#        proj: CAR
#        skydir: [83, 22]
#        width: [5, 5]
#        offset_max: 3 deg
#        axes:
#            e_reco:
#                lo_bnd: 0.01
#                hi_bnd: 100
#                nbin: 73
#                unit: TeV
#                interp: log
#            e_true:
#                lo_bnd: 0.01
#                hi_bnd: 315
#                nbin: 109
#                unit: TeV
#                interp: log

    model:
        description: "Model serialized components and parameters."
        type: object
        additionalProperties: false
        default: {}
        properties:
            components:
                description: "List of component models."
                type: array
                items:
                    type: object
                    additionalProperties: false
                    properties:
                        name: {type: string}
                        spatial:
                            "$ref": "#/definitions/model_components"
                        spectral:
                            "$ref": "#/definitions/model_components"
#    model:
#        components:
#            - name: source
#              spatial:
#                    parameters:
#                    - factor: 0.0
#                      frozen: false
#                      max: 180.0
#                      min: -180.0
#                      name: lon_0
#                      scale: 1.0
#                      unit: deg
#                      value: 0.0
#                    - factor: 0.0
#                      frozen: false
#                      max: 90.0
#                      min: -90.0
#                      name: lat_0
#                      scale: 1.0
#                      unit: deg
#                      value: 0.0
#                    - factor: 1.0
#                      frozen: false
#                      max: .nan
#                      min: 0.0
#                      name: sigma
#                      scale: 1.0
#                      unit: deg
#                      value: 1.0
#                    type: SkyGaussian
#              spectral:
#                    parameters:
#                    - factor: 2.0
#                      frozen: false
#                      max: .nan
#                      min: .nan
#                      name: index
#                      scale: 1.0
#                      unit: ''
#                      value: 2.0
#                    - factor: 1.0e-12
#                      frozen: false
#                      max: .nan
#                      min: .nan
#                      name: amplitude
#                      scale: 1.0
#                      unit: cm-2 s-1 TeV-1
#                      value: 1.0e-12
#                    - factor: 1.0
#                      frozen: true
#                      max: .nan
#                      min: .nan
#                      name: reference
#                      scale: 1.0
#                      unit: TeV
#                      value: 1.0
#                    type: PowerLaw

    fit:
        type: object
        additionalProperties: false
        default: {}
        properties:
            fit_range:
                description: "Energy fit range with units."
                type: object
                additionalProperties: false
                properties:
                    min: {type: number}
                    max: {type: number}
#    fit:
#        fit_range:
#            min: 1 TeV
#            max: 100 Tev

    flux:
        type: object
        additionalProperties: false
        default: {}
        properties:
            fp_binning:
                "$ref": "#/definitions/energy_axis"
#    flux:
#        fp_binning:
#            lo_bnd: 1
#            hi_bnd: 10
#            nbin: 11
#            unit: TeV
#            interp: log

required: [general, observations]

definitions:
    model_components:
        type: object
        additionalProperties: false
        properties:
            type: {type: string}
            parameters:
                type: array
                items:
                    type: object
                    additionalProperties: false
                    properties:
                        name: {type: string}
                        value: {type: number}
                        factor: {type: number}
                        scale: {type: number}
                        unit: {type: string}
                        min: {type: number}
                        max: {type: number}
                        frozen: {type: boolean}
    energy_axis:
        type: object
        additionalProperties: false
        properties:
            name: {type: string}
            lo_bnd: {type: number}
            hi_bnd: {type: number}
            nbin: {type: number}
            unit: {type: string}
            interp:
                type: string
                enum: [lin, log, sqrt]
            node_type:
                type: string
                enum: [edges, center]

        required: [lo_bnd, hi_bnd, nbin, unit]
